#

#  Date: 2022-01-20 15:00:07 +0000 (Thu, 20 Jan 2022)
#

#

#

#

#

# nosemgrep: dockerfile.audit.dockerfile-source-not-pinned.dockerfile-source-not-pinned
FROM jenkins/jenkins:lts

RUN /bin/jenkins-plugin-cli --plugins workflow-aggregator:2.6